# print macro commands on screen
/control/verbose 0

/run/useMaximumLogicalCores


# initialize geometry and physics
/run/initialize

/run/setCut 100 km
/run/setCutForAGivenParticle proton 0.7 mm


# neutrons from a DD+DT(2peak)+TT generator
/gps/source/add 0.55
/gps/particle neutron
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/pos/centre -20 0 0 cm
/gps/pos/radius 10 mm
/gps/pos/halfz 175 mm
/gps/ang/type iso
/gps/ene/type Gauss
/gps/ene/mono 13.8 MeV
/gps/ene/sigma 0.2 MeV

/gps/source/add 0.45
/gps/particle neutron
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/pos/centre -20 0 0 cm
/gps/pos/radius 10 mm
/gps/pos/halfz 175 mm
/gps/ang/type iso
/gps/ene/type Gauss
/gps/ene/mono 14.4 MeV
/gps/ene/sigma 0.2 MeV

/gps/source/add 0.294
/gps/particle neutron
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/pos/centre -20 0 0 cm
/gps/pos/radius 10 mm
/gps/pos/halfz 175 mm
/gps/ang/type iso
/gps/ene/type Gauss
/gps/ene/mono 2.45 MeV
/gps/ene/sigma 0.2 MeV

/gps/source/add 0.00625
/gps/particle neutron
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/pos/centre -20 0 0 cm
/gps/pos/radius 10 mm
/gps/pos/halfz 175 mm
/gps/ang/type iso
/gps/ene/type Gauss
/gps/ene/mono 11.3 MeV
/gps/ene/sigma 0.2 MeV

#MESH SCORING
/score/create/boxMesh DetectorMesh
/score/mesh/boxSize 2.5 20. 20. cm
/score/mesh/nBin 1 400 400
/score/mesh/translate/xyz 38.7373 0. 0. cm
/score/quantity/energyDeposit eDep MeV
/score/filter/particle penergyfilter proton
/score/close
/score/list

#CAMERA MESH, COMMENTED OUT TO PRESERVE COMPUTATION TIME
#/score/create/cylinderMesh CameraMesh
#/score/mesh/cylinderSize 44. 63.5 mm 
#/score/mesh/nBin 100 1 80
#/score/mesh/translate/xyz 112.5 0. 0. cm
#/score/mesh/rotate/rotateY 90 deg
#/score/quantity/nOfTrack nNeutronTrack
#/score/filter/particle neutronFilter neutron
#/score/close
#/score/list

# turn on progress report
/run/verbose 2
/control/verbose 0
/run/verbose 0
/event/verbose 0
/tracking/verbose 0
/process/verbose 0
# start simulation
/run/beamOn 1000000000
/run/beamOn 1000000000
/run/beamOn 1000000000
/run/beamOn 1000000000


/score/dumpQuantityToFile DetectorMesh eDep energy_per_mm2_10m.txt
#/score/dumpQuantityToFile CameraMesh nNeutronTrack Neutron_entries_on_camera.txt

