# print macro commands on screen
/control/verbose 0

/run/useMaximumLogicalCores


# initialize geometry and physics
/run/initialize


/run/setCut 100 km
/run/setCutForAGivenParticle proton 0.7 mm




# neutrons from a PuBe generator
/gps/particle neutron
/gps/energy 2.5 MeV
/gps/pos/type Plane
/gps/pos/shape Rectangle
/gps/pos/centre 0 0 0 cm
/gps/pos/rot1 0 0 1
/gps/pos/rot2 0 1 0
/gps/pos/halfx 20 cm
/gps/pos/halfy 14.8 cm
/gps/ang/type iso




#/vis/open OGL  # OpenGL visualization driver

# Configure visualization attributes
#/vis/viewer/set/autoRefresh true  # Automatically refresh the viewer after commands
#/vis/drawVolume  # Draw the full geometry
#/vis/scene/add/axes 0 0 0 10 cm  # Add axes at origin (length 10 cm)
#/vis/scene/add/gps

#/vis/viewer/set/viewpointThetaPhi 90 0
#/vis/viewer/set/upVector 0 0 1
#/vis/viewer/set/lineSegmentsPerCircle 100  # Smooth circles and cylinders
#/vis/viewer/zoomTo 1.5  # Adjust zoom level (optional)

#/vis/scene/add/trajectories
#/vis/scene/endOfEventAction accumulate 

# Start the visualization
#/vis/viewer/flush
#/vis/viewer/update


#MESH SCORING
/score/create/boxMesh DetectorMesh
/score/mesh/boxSize 2.5 20. 20. cm
/score/mesh/nBin 1 400 400
/score/mesh/translate/xyz 50. 0. 0. cm
/score/quantity/energyDeposit eDep MeV
/score/filter/particle penergyfilter proton
/score/close
/score/list





# turn on progress report
/control/verbose 0
/run/verbose 0
/event/verbose 0
/tracking/verbose 0
/process/verbose 0
# start simulation
/run/beamOn 2000000



/score/dumpQuantityToFile DetectorMesh eDep energy_per_mm2_5m.txt

