# print macro commands on screen
/control/verbose 0


/physics_lists/select QGSP_BIC


# Initialize with some optimisations
/run/useMaximumLogicalCores
/run/initialize

/run/setCut 100 km
/run/setCutForRegion Scintillator 0.7 mm




# Gamma addon source, optimised for 7.7x lower Gy 
/gps/particle gamma
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/pos/centre 0 0 0 cm
/gps/pos/radius 10 mm
/gps/pos/halfz 175 mm
/gps/ang/type iso
/gps/ene/type Gauss
/gps/ene/mono 400 keV
/gps/ene/sigma 50 keV
/gps/ang/mintheta 86.19434789 deg
/gps/ang/maxtheta 93.80565211 deg
/gps/ang/minphi 176.1859252 deg
/gps/ang/maxphi 183.8140748 deg
#/gps/number 1000000
/gps/number 1000

#MESH SCORING
/score/create/boxMesh DetectorMesh
/score/mesh/boxSize 2.5 20. 20. cm
/score/mesh/nBin 1 1 1
/score/mesh/translate/xyz 300 0. 0. cm
/score/quantity/energyDeposit eDep2 MeV
/score/filter/particle genergyfilter gamma
/score/close
/score/list


# turn on progress report
/run/verbose 2
/control/verbose 0
/run/verbose 0
/event/verbose 0
/tracking/verbose 0
/process/verbose 0
# start simulation
#/run/beamOn 105000000
#gamma real 105000000000000
#gamma to neutron real 1050000 for 7.7
#gamma to neutron real 131250 for 1
/run/beamOn 10200
#ran 10200000 to 10 got 1 to 1
#1020000 to 1






/score/dumpQuantityToFile DetectorMesh eDep2 genergy_per_mm2_10m.txt


