# print macro commands on screen
/control/verbose 0
/particle/ImpBiasMode gamma

/physics_lists/select QGSP_BIC

/particle/EnableImpBias true
/particle/ImpBiasXMin -5 cm
/particle/ImpBiasXMax  54 cm
/particle/ImpBiasHalfY 25 cm
/particle/ImpBiasHalfZ 25 cm

/particle/ImpBiasNSlabs 8
/particle/ImpBiasWorldImportance 1.0
/particle/ImpBiasRatio 1.9
# Initialize with some optimisations
/run/useMaximumLogicalCores
/run/initialize

/run/setCut 100 km
/run/setCutForRegion Scintillator 0.7 mm




# Gamma addon source, optimised for 7.7x lower Gy 
/gps/particle gamma
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/pos/centre 0 0 0 cm
/gps/pos/radius 10 mm
/gps/pos/halfz 175 mm
/gps/ang/type iso
/gps/ene/type Gauss
/gps/ene/mono 400 keV
/gps/ene/sigma 50 keV
/gps/ang/mintheta 69 deg
/gps/ang/maxtheta 111 deg
/gps/ang/minphi 158 deg
/gps/ang/maxphi 202 deg
#/gps/number 1000000
/gps/number 100

#MESH SCORING
/score/create/boxMesh DetectorMesh
/score/mesh/boxSize 2.5 20. 20. cm
/score/mesh/nBin 5 400 400
/score/mesh/translate/xyz 50 0. 0. cm
/score/quantity/energyDeposit eDep2 MeV
/score/filter/particle genergyfilter gamma
/score/close
/score/list


# turn on progress report
/run/verbose 2
/control/verbose 0
/run/verbose 0
/event/verbose 0
/tracking/verbose 0
/process/verbose 0
# start simulation
#/run/beamOn 105000000
#gamma real 105000000000000
#gamma to neutron real 1050000 for 7.7
#gamma to neutron real 131250 for 1
/run/beamOn 10000






/score/dumpQuantityToFile DetectorMesh eDep2 genergy_per_mm2_10m.txt


